export const heroBanners = {
  home: {
    imageSrc: '/images/banners/images-4.jpg',
    imageAlt: 'San Lorenzo Valley banner photo (images-4)',
    imagePosition: 'center 44%',
    accent: 'teal',
    assetKey: 'home',
  },
  records: {
    imageSrc: '/images/banners/images.jpg',
    imageAlt: 'San Lorenzo Valley banner photo (images)',
    imagePosition: 'center 38%',
    accent: 'coral',
    assetKey: 'records',
  },
  seasons: {
    imageSrc: '/images/banners/images-1.jpg',
    imageAlt: 'San Lorenzo Valley banner photo (images-1)',
    imagePosition: 'center 44%',
    accent: 'gold',
    assetKey: 'seasons',
  },
  playoffs: {
    imageSrc: '/images/banners/images-2.jpg',
    imageAlt: 'San Lorenzo Valley banner photo (images-2)',
    imagePosition: 'center 30%',
    accent: 'gold',
    assetKey: 'playoffs',
  },
  draft: {
    imageSrc: '/images/banners/images-3.jpg',
    imageAlt: 'San Lorenzo Valley banner photo (images-3)',
    imagePosition: 'center 42%',
    accent: 'teal',
    assetKey: 'draft',
  },
  trades: {
    imageSrc: '/images/banners/Big+Basin+Redwoods.webp',
    imageAlt: 'Big Basin Redwoods in San Lorenzo Valley',
    imagePosition: 'center 42%',
    accent: 'coral',
    assetKey: 'trades',
  },
  teams: {
    imageSrc: '/images/banners/Downtown+Boulder+Creek.webp',
    imageAlt: 'Downtown Boulder Creek in San Lorenzo Valley',
    imagePosition: 'center 34%',
    accent: 'teal',
    assetKey: 'teams',
  },
  headToHead: {
    imageSrc: '/images/banners/Roaring+Camp.webp',
    imageAlt: 'Roaring Camp in the San Lorenzo Valley area',
    imagePosition: 'center 50%',
    accent: 'rose',
    assetKey: 'headToHead',
  },
  matchups: {
    imageSrc: '/images/banners/images.jpg',
    imageAlt: 'San Lorenzo Valley banner photo (images)',
    imagePosition: 'center 45%',
    accent: 'rose',
    assetKey: 'matchups',
  },
  rosters: {
    imageSrc: '/images/banners/images-4.jpg',
    imageAlt: 'San Lorenzo Valley banner photo (images-4)',
    imagePosition: 'center 40%',
    accent: 'teal',
    assetKey: 'rosters',
  },
}
